version: '3.8'

services:
  postgres_identity:
    image: postgres:15-alpine
    container_name: postgres_identity
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: identity_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_identity_data:/var/lib/postgresql/data
    networks:
      - shift_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d identity_service"]
      interval: 10s
      timeout: 5s
      retries: 5

identity-service:
    image: ghcr.io/integrationproject-groep1/identity-service:latest
    container_name: identity_service
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      
      - RABBITMQ_HOST=rabbitmq_broker
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=/
      - PYTHONUNBUFFERED=1
    networks:
      - shift_net

networks:
  shift_net:
    external: true
    name: shiftfestival_network

volumes:
  postgres_identity_data:
